import { createRoute, OpenAPIHono, z } from '@hono/zod-openapi';
import { streamSSE } from 'hono/streaming';
import { Buffer } from 'node:buffer';
import { createDecipheriv, createHash } from 'node:crypto';
import * as zm from 'zod/mini';
import type { ContextVariables, EnvVars } from '~/types.js';

const app = new OpenAPIHono<{ Bindings: EnvVars; Variables: ContextVariables }>();

const CacheControlEphemeral = z
	.object({
		type: z.enum(['ephemeral']).default('ephemeral'),
		ttl: z.enum(['5m', '1h']).default('5m').openapi({ description: 'The time-to-live for the cache control breakpoint.' }),
	})
	.default({ type: 'ephemeral', ttl: '5m' })
	.openapi('CacheControlEphemeral', { description: 'Top-level cache control automatically applies a cache_control marker to the last cacheable block in the request.' });

const Message = z
	.object({
		id: z.string(),
		container: z
			.object({
				id: z.string(),
				expires_at: z.iso.datetime(),
			})
			.optional()
			.openapi('Container'),
		content: z
			.array(
				z.discriminatedUnion('type', [
					z
						.object({
							citations: z.array(z.record(z.string(), z.unknown())).optional(),
							text: z.string(),
							type: z.literal('text'),
						})
						.openapi('TextBlock'),
					z
						.object({
							signature: z.string().optional(),
							thinking: z.string(),
							type: z.literal('thinking'),
						})
						.openapi('ThinkingBlock'),
					z
						.object({
							data: z.string(),
							type: z.literal('redacted_thinking'),
						})
						.openapi('RedactedThinkingBlock'),
					z
						.object({
							id: z.string(),
							caller: z
								.discriminatedUnion('type', [
									z
										.object({
											type: z.literal('direct'),
										})
										.openapi('DirectCaller'),
									z
										.object({
											tool_id: z.string(),
											type: z.literal('code_execution_20250825'),
										})
										.openapi('ServerToolCaller'),
									z
										.object({
											tool_id: z.string(),
											type: z.literal('code_execution_20260120'),
										})
										.openapi('ServerToolCaller20260120'),
								])
								.optional(),
							input: z.record(z.string(), z.unknown()),
							name: z.string(),
							type: z.literal('tool_use'),
						})
						.openapi('ToolUseBlock'),
				]),
			)
			.openapi({ description: 'Content generated by the model.' }),
		model: z.string().openapi({ description: 'The model that will complete your prompt.' }),
		role: z.literal('assistant').openapi({ description: 'Conversational role of the generated message.' }),
		stop_details: z
			.object({
				category: z.enum(['cyber', 'bio', 'frontier_llm', 'reasoning_extraction']),
				explanation: z.string(),
				type: z.literal('refusal'),
			})
			.optional()
			.openapi('RefusalStopDetails'),
		stop_reason: z.enum(['end_turn', 'max_tokens', 'stop_sequence', 'tool_use', 'pause_turn', 'refusal']).openapi('StopReason', { description: 'The reason that we stopped.' }),
		stop_sequence: z.string().nullable().openapi({ description: 'Which custom stop sequence was generated, if any.' }),
		type: z.literal('message'),
		usage: z
			.object({
				cache_creation: z
					.object({
						ephemeral_1h_input_tokens: z.int().nonnegative().optional(),
						ephemeral_5m_input_tokens: z.int().nonnegative().optional(),
					})
					.optional()
					.openapi('CacheCreation', { description: 'Breakdown of cached tokens by TTL' }),
				cache_creation_input_tokens: z.int().nonnegative().optional(),
				cache_read_input_tokens: z.int().nonnegative().optional(),
				inference_geo: z.string().optional().openapi({ description: 'The geographic region where inference processing occurred.' }),
				input_tokens: z.int().nonnegative().optional(),
				output_tokens: z.int().nonnegative().optional(),
			})
			.openapi('Usage'),
	})
	.openapi('Message');

const RawMessageStreamEvent = z
	.discriminatedUnion('type', [
		z
			.object({
				message: z.record(z.string(), z.unknown()),
				type: z.literal('message_start'),
			})
			.openapi('RawMessageStartEvent'),
		z
			.object({
				delta: z.record(z.string(), z.unknown()),
				type: z.literal('message_delta'),
				usage: z
					.object({
						cache_creation_input_tokens: z.int().nonnegative().optional(),
						cache_read_input_tokens: z.int().nonnegative().optional(),
						input_tokens: z.int().nonnegative().optional(),
						output_tokens: z.int().nonnegative().optional(),
						output_tokens_details: z
							.object({
								thinking_tokens: z.int().nonnegative().optional(),
							})
							.optional()
							.openapi('OutputTokensDetails'),
					})
					.optional()
					.openapi('MessageDeltaUsage'),
			})
			.openapi('RawMessageDeltaEvent'),
		z
			.object({
				type: z.literal('message_stop'),
			})
			.openapi('RawMessageStopEvent'),
		z
			.object({
				content_block: z.record(z.string(), z.unknown()),
				index: z.int().nonnegative(),
				type: z.literal('content_block_start'),
			})
			.openapi('RawContentBlockStartEvent'),
		z
			.object({
				delta: z.record(z.string(), z.unknown()).openapi('RawContentBlockDelta'),
				index: z.int().nonnegative(),
				type: z.literal('content_block_delta'),
			})
			.openapi('RawContentBlockDeltaEvent'),
		z
			.object({
				index: z.int().nonnegative(),
				type: z.literal('content_block_stop'),
			})
			.openapi('RawContentBlockStopEvent'),
	])
	.openapi('RawMessageStreamEvent');

function finishReasonToStopReason(reason: string): 'end_turn' | 'max_tokens' | 'stop_sequence' | 'tool_use' {
	switch (reason) {
		case 'length':
			return 'max_tokens';
		case 'tool_calls':
		case 'function_call':
			return 'tool_use';
		default:
			return 'end_turn';
	}
}

app.openapi(
	createRoute({
		method: 'post',
		path: '/',
		request: {
			body: {
				content: {
					'application/json': {
						schema: z.object({
							max_tokens: z.int().positive().openapi({ description: 'The maximum number of tokens to generate before stopping.' }),
							messages: z.array(
								z
									.object({
										content: z.union([
											z.string(),
											z
												.array(
													z
														.discriminatedUnion('type', [
															z
																.object({
																	text: z.string(),
																	type: z.literal('text'),
																})
																.openapi('TextBlockParam'),
															z
																.object({
																	source: z.discriminatedUnion('type', [
																		z
																			.object({
																				data: z.string(),
																				media_type: z.enum(['image/jpeg', 'image/png', 'image/gif', 'image/webp']),
																				type: z.literal('base64'),
																			})
																			.openapi('Base64ImageSource'),
																		z
																			.object({
																				type: z.literal('url'),
																				url: z.url({ pattern: z.regexes.domain }),
																			})
																			.openapi('URLImageSource'),
																	]),
																	type: z.literal('image'),
																	cache_control: CacheControlEphemeral,
																})
																.openapi('ImageBlockParam'),
															z
																.object({
																	source: z.discriminatedUnion('type', [
																		z
																			.object({
																				data: z.string(),
																				media_type: z.literal('application/pdf'),
																				type: z.literal('base64'),
																			})
																			.openapi('Base64PDFSource'),
																		z
																			.object({
																				data: z.string(),
																				media_type: z.literal('text/plain'),
																				type: z.literal('text'),
																			})
																			.openapi('PlainTextSource'),
																		z
																			.object({
																				content: z.unknown(),
																				type: z.literal('content'),
																			})
																			.openapi('ContentBlockSource'),
																		z
																			.object({
																				type: z.literal('url'),
																				url: z.url({ pattern: z.regexes.domain }),
																			})
																			.openapi('URLPDFSource'),
																	]),
																	type: z.literal('document'),
																})
																.openapi('DocumentBlockParam'),
														])
														.openapi('ContentBlockParam'),
												)
												.openapi('ContentBlockParams'),
										]),
										role: z.enum(['user', 'assistant', 'system']),
									})
									.openapi('MessageParam'),
							),
							model: z
								.string()
								.startsWith('claude|')
								.refine((model) => {
									const [prefix, cipherText] = model.split('|');

									return prefix && cipherText && zm.base64url().check(zm.trim(), zm.minLength(1)).safeParse(cipherText).success;
								})
								.transform((model) => model.split('|')[1]!)
								.openapi('Model', { description: 'The model that will complete your prompt.' }),
							cache_control: CacheControlEphemeral,
							container: z.string().optional().openapi({ description: 'Container identifier for reuse across requests.' }),
							inference_geo: z.string().optional().openapi({ description: "Specifies the geographic region for inference processing. If not specified, the workspace's `default_inference_geo` is used." }),
							metadata: z
								.object({
									user_id: z.string().optional().openapi({ description: 'An external identifier for the user who is associated with the request.' }),
								})
								.optional()
								.openapi('Metadata', { description: 'An object describing metadata about the request.' }),
							output_config: z
								.object({
									effort: z.enum(['low', 'medium', 'high']).optional(),
									format: z
										.object({
											properties: z.record(z.string(), z.unknown()),
											type: z.literal('json_schema'),
										})
										.optional(),
								})
								.optional()
								.openapi(' OutputConfig'),
							service_tier: z.enum(['auto', 'standard_only']).optional().openapi({ description: 'Determines whether to use priority capacity (if available) or standard capacity for this request.' }),
							stop_sequences: z.array(z.string()).optional().openapi({ description: 'Custom text sequences that will cause the model to stop generating.' }),
							stream: z.boolean().optional().openapi({ description: 'Whether to incrementally stream the response using server-sent events.' }),
							system: z
								.union([
									z.string(),
									z.array(
										z
											.object({
												text: z.string(),
												type: z.literal('text'),
												cache_control: CacheControlEphemeral,
											})
											.openapi('TextBlockParam'),
									),
								])
								.optional()
								.openapi({ description: 'System prompt.' }),
							temperature: z.number().min(0.0).max(1.0).default(1.0).openapi({ deprecated: true, description: 'Amount of randomness injected into the response.' }),
							thinking: z
								.discriminatedUnion('type', [
									z
										.object({
											budget_tokens: z.int().min(1024).openapi({ description: 'Determines how many tokens Claude can use for its internal reasoning process. Larger budgets can enable more thorough analysis for complex problems, improving response quality.' }),
											type: z.literal('enabled'),
											display: z.enum(['summarized', 'omitted']).default('summarized').openapi({ description: 'Controls how thinking content appears in the response. When set to `summarized`, thinking is returned normally. When set to `omitted`, thinking content is redacted but a signature is returned for multi-turn continuity.' }),
										})
										.openapi('ThinkingConfigEnabled'),
									z
										.object({
											type: z.literal('disabled'),
										})
										.openapi('ThinkingConfigDisabled'),
									z
										.object({
											type: z.literal('adaptive'),
											display: z.enum(['summarized', 'omitted']).default('summarized').openapi({ description: 'Controls how thinking content appears in the response. When set to `summarized`, thinking is returned normally. When set to `omitted`, thinking content is redacted but a signature is returned for multi-turn continuity.' }),
										})
										.openapi('ThinkingConfigAdaptive'),
								])
								.optional()
								.openapi('ThinkingConfigParam', { description: "Configuration for enabling Claude's extended thinking." }),
							tool_choice: z
								.discriminatedUnion('type', [
									z
										.object({
											type: z.literal('auto'),
											disable_parallel_tool_use: z.boolean().default(false).openapi({ description: 'Whether to disable parallel tool use.' }),
										})
										.openapi('ToolChoiceAuto'),
									z
										.object({
											type: z.literal('any'),
											disable_parallel_tool_use: z.boolean().default(false).openapi({ description: 'Whether to disable parallel tool use.' }),
										})
										.openapi('ToolChoiceAny'),
									z
										.object({
											name: z.string(),
											type: z.literal('tool'),
											disable_parallel_tool_use: z.boolean().default(false).openapi({ description: 'Whether to disable parallel tool use.' }),
										})
										.openapi('ToolChoiceTool'),
									z
										.object({
											type: z.literal('none'),
										})
										.openapi('ToolChoiceNone'),
								])
								.optional()
								.openapi('ToolChoice'),
							tools: z
								.array(
									z.looseObject({
										name: z.string(),
										description: z.string().optional(),
										input_schema: z.looseObject({
											type: z.literal('object'),
											properties: z.record(z.string(), z.unknown()).optional(),
											required: z.array(z.string()).optional(),
										}),
									}),
								)
								.optional(),
							top_k: z.number().min(0.0).max(1.0).default(1.0).openapi({ deprecated: true, description: 'Only sample from the top K options for each subsequent token.' }),
							top_p: z.number().min(0.0).max(1.0).default(1.0).openapi({ deprecated: true, description: 'Use nucleus sampling.' }),
						}),
					},
				},
				required: true,
			},
		},
		responses: {
			200: {
				content: {
					'application/json': {
						schema: Message,
					},
					'text/event-stream': {
						schema: RawMessageStreamEvent,
					},
				},
				description: '',
			},
		},
	}),
	async (c) => {
		// console.debug('json', await cloneRawRequest(c.req).then((request) => request.json()));
		const json = c.req.valid('json');

		const rawModel = Buffer.from(json.model, 'base64url');
		const decipher = createDecipheriv(
			'chacha20-poly1305',
			// Key must be exactly 256 bits/32 bytes for `chacha20-poly1305`
			createHash('sha256').update(c.env.DUMMY_SECRET).digest(),
			rawModel.subarray(0, 96 / 8),
			{ authTagLength: 16 },
		);
		decipher.setAuthTag(rawModel.subarray(96 / 8, 96 / 8 + 16));
		const model = Buffer.concat([decipher.update(rawModel.subarray(96 / 8 + 16)), decipher.final()]).toString('utf8');

		// Short-circuit probe requests without calling Workers AI.
		// Claude Desktop sends max_tokens=1 with a minimal single message to verify
		// gateway connectivity before marking it available. Workers AI cold-start
		// latency exceeds Claude Desktop's probe timeout, so we return a fast canned
		// response that satisfies the probe format check.
		const [probeMsg] = json.messages;
		if (json.max_tokens === 1 && !json.stream && json.messages.length === 1 && probeMsg !== undefined) {
			const probeMsgContent = probeMsg.content;
			let isProbeMsg = false;
			if (typeof probeMsgContent === 'string') {
				isProbeMsg = probeMsgContent.trim().length <= 2;
			} else if (probeMsgContent.length === 1) {
				const firstBlock = probeMsgContent[0];
				isProbeMsg = firstBlock?.type === 'text' && firstBlock.text.trim().length <= 2;
			}
			if (isProbeMsg) {
				return c.json({
					id: `msg_${crypto.randomUUID()}`,
					type: 'message',
					role: 'assistant',
					content: [{ type: 'text', text: ' ' }],
					model,
					stop_reason: 'max_tokens',
					stop_sequence: null,
					usage: { input_tokens: 1, output_tokens: 1 },
				} satisfies z.input<typeof Message>);
			}
		}

		// Build the messages array for Workers AI
		const messages: ChatCompletionMessageParam[] = [];

		// Prepend system prompt if provided via the top-level system parameter
		if (json.system) {
			const systemText = typeof json.system === 'string' ? json.system : json.system.map((b) => b.text).join('\n');
			messages.push({ role: 'system', content: systemText });
		}

		// Convert Anthropic messages to Workers AI ChatCompletionMessageParam format
		for (const message of json.messages) {
			if (typeof message.content === 'string') {
				messages.push({ role: message.role, content: message.content });
				continue;
			}

			if (message.role === 'user') {
				const parts: UserMessageContentPart[] = [];
				for (const block of message.content) {
					if (block.type === 'text') {
						parts.push({ type: 'text', text: block.text });
					} else if (block.type === 'image') {
						const src = block.source;
						const url = src.type === 'base64' ? `data:${src.media_type};base64,${src.data}` : src.url;
						parts.push({ type: 'image_url', image_url: { url } });
					} else if (block.type === 'document') {
						const src = block.source;
						// Plain text documents: pass as text
						if (src.type === 'text') {
							parts.push({ type: 'text', text: src.data });
						}
						// PDF and other document types are not natively supported; skip
					}
				}
				messages.push({ role: 'user', content: parts });
			} else {
				// assistant or system: extract text blocks
				const textContent = message.content
					.filter((b): b is { type: 'text'; text: string } => b.type === 'text')
					.map((b) => b.text)
					.join('\n');
				messages.push({ role: message.role, content: textContent });
			}
		}

		// Convert Anthropic tool_choice to Workers AI format
		let toolChoice: ChatCompletionToolChoiceOption | undefined;
		if (json.tool_choice) {
			switch (json.tool_choice.type) {
				case 'auto':
					toolChoice = 'auto';
					break;
				case 'any':
					toolChoice = 'required';
					break;
				case 'none':
					toolChoice = 'none';
					break;
				case 'tool':
					toolChoice = { type: 'function', function: { name: json.tool_choice.name } };
					break;
			}
		}

		let metadata: Record<string, string> = {};
		try {
			const parsedMetadata = zm.record(z.string(), z.string()).parse(JSON.parse(json.metadata?.user_id ?? '{}'));
			// Ai Gateway has a limit of 5 metadata fields
			if (Object.keys(parsedMetadata).length <= 5) {
				metadata = parsedMetadata;
			} else {
				const first4 = Object.fromEntries(Object.entries(parsedMetadata).slice(0, 4));
				const remainder = Object.fromEntries(Object.entries(parsedMetadata).slice(4));
				metadata = { ...first4, remainder: JSON.stringify(remainder) };
			}
			// eslint-disable-next-line @typescript-eslint/no-unused-vars
		} catch (error) {
			if (json.metadata?.user_id) metadata['user_id'] = json.metadata.user_id;
		}

		const response = await c.env.AI.run(
			model,
			{
				messages,
				stream: json.stream,
				max_tokens: json.max_tokens,
				temperature: json.temperature,
				top_p: json.top_p,
				stop: json.stop_sequences,
				tools: json.tools?.map((tool) => ({
					type: 'function' as const,
					function: {
						name: tool.name,
						description: tool.description,
						parameters: tool.input_schema,
					},
				})),
				reasoning_effort: json.thinking?.type === 'adaptive' ? 'medium' : undefined,
				...(toolChoice !== undefined && { tool_choice: toolChoice }),
				...(json.stream && { stream_options: { include_usage: true } }),
			},
			{
				queueRequest: false,
				gateway: {
					cacheTtl: json.cache_control.ttl === '5m' ? 5 * 60 : json.cache_control.ttl === '1h' ? 60 * 60 : 0,
					id: c.env.GATEWAY,
					metadata,
				},
				signal: c.req.raw.signal,
			},
		);

		if (json.stream) {
			const workersAIStream = response as unknown as ReadableStream;
			const messageId = `msg_${crypto.randomUUID()}`;
			const reader = workersAIStream.pipeThrough(new TextDecoderStream()).getReader();

			return streamSSE(c, async (stream) => {
				// Stop the upstream AI call the moment the client is gone
				// eslint-disable-next-line @typescript-eslint/no-empty-function
				stream.onAbort(() => reader.cancel().catch(() => {}));
				c.req.raw.signal.onabort = () => stream.abort();

				let buffer = '';
				let messageStarted = false;
				let blockIndex = 0;
				let blockOpen = false;
				let inputTokens = 0;
				let outputTokens = 0;
				let stopReason: 'end_turn' | 'max_tokens' | 'stop_sequence' | 'tool_use' = 'end_turn';

				const sendMessageStart = async () => {
					await stream.writeSSE({
						event: 'message_start',
						data: JSON.stringify({
							type: 'message_start',
							message: {
								id: messageId,
								type: 'message',
								role: 'assistant',
								content: [],
								model,
								stop_reason: null,
								stop_sequence: null,
								usage: { input_tokens: inputTokens, output_tokens: 0 },
							},
						}),
					});
					messageStarted = true;
				};

				const closeBlock = async () => {
					if (blockOpen) {
						await stream.writeSSE({ event: 'content_block_stop', data: JSON.stringify({ type: 'content_block_stop', index: blockIndex }) });
						blockOpen = false;
					}
				};

				let result = await reader.read();

				while (!result.done) {
					buffer += result.value;
					const segments = buffer.split('\n\n');
					buffer = segments.pop() ?? '';

					for (const segment of segments) {
						const dataLine = segment.split('\n').find((l) => l.startsWith('data:'));
						if (!dataLine) continue;

						const payload = dataLine.slice(5).trim();
						console.debug('payload', payload);

						if (payload === '[DONE]') {
							if (!messageStarted) await sendMessageStart();
							await closeBlock();
							await stream.writeSSE({
								event: 'message_delta',
								data: JSON.stringify({
									type: 'message_delta',
									delta: { stop_reason: stopReason, stop_sequence: null },
									usage: { output_tokens: outputTokens },
								}),
							});
							await stream.writeSSE({ event: 'message_stop', data: JSON.stringify({ type: 'message_stop' }) });
							await stream.close();
							return;
						}

						let parsed: {
							response?: string | null;
							usage?: { prompt_tokens?: number; completion_tokens?: number };
							choices?: { delta?: { content?: string | null; tool_calls?: { id?: string; type?: string; function?: { name?: string; arguments?: string } }[] | null }; finish_reason?: string | null }[];
							tool_calls?: { id: string; type: string; function?: { name: string; arguments: string } }[];
						};
						try {
							parsed = JSON.parse(payload) as typeof parsed;
						} catch {
							continue;
						}

						// Capture usage (trailing native summary chunk or stream_options include_usage)
						if (parsed.usage) {
							inputTokens = parsed.usage.prompt_tokens ?? inputTokens;
							outputTokens = parsed.usage.completion_tokens ?? outputTokens;
						}

						// Track finish_reason from OpenAI-compat choices
						const firstChoice = parsed.choices?.[0];
						const chunkFinishReason = firstChoice?.finish_reason;
						if (chunkFinishReason) stopReason = finishReasonToStopReason(chunkFinishReason);

						if (!messageStarted) await sendMessageStart();

						// Text delta: OpenAI-compat choices[0].delta.content (with native response string fallback)
						const deltaContent = firstChoice?.delta?.content;
						const textDelta = typeof deltaContent === 'string' ? deltaContent : typeof parsed.response === 'string' ? parsed.response : null;
						if (textDelta) {
							if (!blockOpen) {
								await stream.writeSSE({
									event: 'content_block_start',
									data: JSON.stringify({ type: 'content_block_start', index: blockIndex, content_block: { type: 'text', text: '' } }),
								});
								blockOpen = true;
							}
							await stream.writeSSE({
								event: 'content_block_delta',
								data: JSON.stringify({ type: 'content_block_delta', index: blockIndex, delta: { type: 'text_delta', text: textDelta } }),
							});
						}

						// Tool call chunk — Workers AI may emit tool_calls alongside response
						if (parsed.tool_calls?.length) {
							// Close any open text block before starting tool_use blocks
							await closeBlock();
							for (const tc of parsed.tool_calls) {
								if (tc.type === 'function' && tc.function) {
									const toolBlockIndex = blockOpen ? ++blockIndex : blockIndex;
									await stream.writeSSE({
										event: 'content_block_start',
										data: JSON.stringify({
											type: 'content_block_start',
											index: toolBlockIndex,
											content_block: { type: 'tool_use', id: tc.id, name: tc.function.name, input: {} },
										}),
									});
									await stream.writeSSE({
										event: 'content_block_delta',
										data: JSON.stringify({
											type: 'content_block_delta',
											index: toolBlockIndex,
											delta: { type: 'input_json_delta', partial_json: tc.function.arguments },
										}),
									});
									await stream.writeSSE({
										event: 'content_block_stop',
										data: JSON.stringify({ type: 'content_block_stop', index: toolBlockIndex }),
									});
									blockIndex = toolBlockIndex + 1;
								}
							}
						}
					}

					if (stream.closed || stream.aborted) break;
					result = await reader.read();
				}

				// Stream ended without explicit [DONE] — flush gracefully
				if (!stream.closed && !stream.aborted) {
					if (!messageStarted) await sendMessageStart();
					await closeBlock();
					await stream.writeSSE({
						event: 'message_delta',
						data: JSON.stringify({
							type: 'message_delta',
							delta: { stop_reason: stopReason, stop_sequence: null },
							usage: { output_tokens: outputTokens },
						}),
					});
					await stream.writeSSE({ event: 'message_stop', data: JSON.stringify({ type: 'message_stop' }) });
				}
			});
		} else {
			const buffered = response as ChatCompletionsOutput;
			const choice = buffered.choices[0];

			type ContentBlock = z.input<typeof Message>['content'][number];
			const content: ContentBlock[] = [];

			if (choice?.message.content) {
				content.push({ type: 'text', text: choice.message.content });
			}

			if (choice?.message.tool_calls) {
				for (const tc of choice.message.tool_calls) {
					if (tc.type === 'function') {
						let input: Record<string, unknown> = {};
						try {
							input = JSON.parse(tc.function.arguments) as Record<string, unknown>;
						} catch {
							/* leave empty */
						}
						content.push({
							type: 'tool_use',
							id: tc.id,
							name: tc.function.name,
							input,
						});
					}
				}
			}

			const stopReason = finishReasonToStopReason(choice?.finish_reason ?? 'stop');

			return c.json({
				id: buffered.id,
				type: 'message',
				role: 'assistant',
				content,
				model,
				stop_reason: stopReason,
				stop_sequence: null,
				usage: {
					input_tokens: buffered.usage?.prompt_tokens ?? 0,
					output_tokens: buffered.usage?.completion_tokens ?? 0,
				},
			} satisfies z.input<typeof Message>);
		}
	},
);

export default app;
